### PR TITLE
Update Program self references

### LINKED ISSUE #61: Update Name Instances
Due to our recent name change we need to update all the instances of the old name and IRC channel in the docs and code! This should be really easy to do and would be a great beginner PR!!

### PR DESCRIPTION
**Pull request by AndroidKitKat**
# Description

Updates all instances of commandChan and changes them to TerminusBrowse

Fixes #61 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style of this project
- [X] I have performed a self-review of my own code
- [X] My code is self documenting
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new major crashes/bugs
- [X] Any new features/functionality have corresponding test cases added

### CODE REVIEW

**Comment by AndroidKitKat** [comment]
Will update screenshots when home from work.

**Comment by wtheisen** [comment]
we need an 'r' now

**Comment by AndroidKitKat** [comment]
Will fix. Thanks for letting me know.

**Comment by AndroidKitKat** [comment]
Updated, LMK if this conflicts with anything.

**Comment by AndroidKitKat** [comment]
Forgot screenshots, I'll get those

**Comment by wtheisen** [comment]
I'll wait to merge this then until you get screenshots prepared, please make sure that the screenshots are work safe appropriate in terms of their content!

**Comment by AndroidKitKat** [comment]
This should include all requested changes

**Comment by wtheisen** [comment]
Fantastic

**Pull request merged**
