### PR TITLE
Moving towards PEP-8 styled file names

### LINKED ISSUE #88: Conformity to PEP8 File Naming Conventions
### Issue and Steps to Reproduce
Currently files are named in a camel-case style, due to what I originally learned when I started programming. However PEP8 specifies that modules(files) should be named in a snake case manner. It might be good to move towards more compliance with PEP8 style suggestions

### PR DESCRIPTION
**Pull request by iamshnoo**
# Description

PEP 8 tells that modules (filenames) should have short, all-lowercase names, and they can contain underscores.
This PR aims to do just that.

Fixes #88 .

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style of this project
- [X] I have performed a self-review of my own code
- [X] My code is self documenting
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new major crashes/bugs
- [X] Any new features/functionality have corresponding test cases added

### CODE REVIEW

**Comment by wtheisen** [comment]
Hi, while most of this looks fantastic, it looks like there's a few lingering errors related to the views class, I've attached the output from running pytest. 

[test_output.txt](https://github.com/wtheisen/TerminusBrowser/files/5321670/test_output.txt)

**Comment by iamshnoo** [comment]
Screenshot 2020-10-03 at 6 34 46 PM

That's weird, because, on my end, when I run pytest, everything passes. Attached a screenshot above.

**Comment by wtheisen** [comment]
Yeah I'm more than willing the believe that I may have messed something up here, I'll double check!

**Comment by wtheisen** [comment]
Okay I restested and everything seems to work! Sorry it took a few days, work caught up to me.

**Review by wtheisen — APPROVED** [review]
Great :)

**Review by sambattalio — APPROVED** [review]
Ship it 🚢

**Comment by iamshnoo** [comment]
Thank you!

**Review by ginglis13 — APPROVED** [review]
LGTM!

**Pull request merged**
